"""created Investor, Stock, Transaction, Exchange models

Revision ID: f1e5cd3ff662
Revises: 
Create Date: 2023-01-31 20:12:47.321162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e5cd3ff662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('exchange_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('current_stock_price', sa.Numeric(), nullable=True),
    sa.Column('environment_rating', sa.String(), nullable=True),
    sa.Column('social_rating', sa.String(), nullable=True),
    sa.Column('governance_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('exchange_id')
    )
    op.create_table('investor',
    sa.Column('investor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investor_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_logged_in', sa.Boolean(), nullable=False),
    sa.Column('cash_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_shares_buys', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_shares_sales', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_shares_cash_value', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_assets_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_e_rating', sa.String(), server_default='', nullable=False),
    sa.Column('current_s_rating', sa.String(), server_default='', nullable=False),
    sa.Column('current_g_rating', sa.String(), server_default='', nullable=False),
    sa.Column('e_goal', sa.String(), server_default='', nullable=False),
    sa.Column('s_goal', sa.String(), server_default='', nullable=False),
    sa.Column('g_goal', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('investor_id')
    )
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('environment_rating', sa.String(), nullable=True),
    sa.Column('social_rating', sa.String(), nullable=True),
    sa.Column('governance_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('current_stock_price', sa.Integer(), nullable=True),
    sa.Column('number_stock_shares', sa.Integer(), nullable=True),
    sa.Column('transaction_total_value', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.investor_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('stock')
    op.drop_table('investor')
    op.drop_table('exchange')
    # ### end Alembic commands ###
