"""adds User, Transaction, and Stock models

Revision ID: f6788a009150
Revises: 
Create Date: 2023-01-25 13:39:22.467085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6788a009150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('environment_score', sa.Integer(), nullable=True),
    sa.Column('social_score', sa.Integer(), nullable=True),
    sa.Column('government_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_logged_in', sa.Boolean(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(), nullable=True),
    sa.Column('total_shares_buys', sa.Integer(), nullable=True),
    sa.Column('total_shares_sales', sa.Integer(), nullable=True),
    sa.Column('total_shares_cash_value', sa.Numeric(), nullable=True),
    sa.Column('total_assets_balance', sa.Numeric(), nullable=True),
    sa.Column('current_e_average_score', sa.Integer(), nullable=True),
    sa.Column('current_s_average_score', sa.Integer(), nullable=True),
    sa.Column('current_g_average_score', sa.Integer(), nullable=True),
    sa.Column('e_goal_average', sa.Integer(), nullable=True),
    sa.Column('s_goal_average', sa.Integer(), nullable=True),
    sa.Column('g_goal_average', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=True),
    sa.Column('stock_name', sa.String(), nullable=True),
    sa.Column('current_stock_price', sa.Numeric(), nullable=True),
    sa.Column('number_stock_shares', sa.Integer(), nullable=True),
    sa.Column('transaction_total_value', sa.Numeric(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('stock')
    # ### end Alembic commands ###
